version: '3.7'

services:
  database_rentx:
    image: postgres
    restart: always
    container_name: database_rentx
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: rentx
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database_rentx
  #   depends_on:
  #     - database_rentx

volumes:
  pgdata:
    driver: local